[package]
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
build = "build.rs"
description = "A safe wrapper around smealum's ctrulib."
license = "https://en.wikipedia.org/wiki/Zlib_License"
links = "ctru"
name = "ctru-rs"
version = "0.4.0"

[dependencies.ctru-sys]
path = "ctru-sys"

[dependencies.alloc_system3ds]
git = "https://github.com/rust3ds/alloc_system3ds"

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"

[lib]
crate-type = ["rlib"]
name = "ctru"
